/*
 * generated by Xtext 2.9.1
 */
package org.team38.assembly


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class LC2200RuntimeModule extends AbstractLC2200RuntimeModule {
}
