/*
 * generated by Xtext 2.9.1
 */
package org.team38.assembly

import org.eclipse.xtext.parser.antlr.ISyntaxErrorMessageProvider

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class LC2200RuntimeModule extends AbstractLC2200RuntimeModule {
	
	def Class<? extends ISyntaxErrorMessageProvider> bindISyntaxErrorMessageProvider() {
		return CustomMessageProvider;
	}
	
}
