/**
 * generated by Xtext 2.9.1
 */
package org.team38.assembly.ui.contentassist;

import org.team38.assembly.ui.contentassist.AbstractLC2200ProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class LC2200ProposalProvider extends AbstractLC2200ProposalProvider {
}
