/*
 * generated by Xtext 2.9.1
 */
package org.team38.assembly.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class LC2200UiModule extends AbstractLC2200UiModule {
}
