/*
 * generated by Xtext 2.9.1
 */
package org.team38.assembly.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class LC2200GrammarAccess extends AbstractGrammarElementFinder {
	
	public class ProgramElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.team38.assembly.LC2200.Program");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cProgramAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cLineEndsAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cLineEndsLineEndParserRuleCall_1_0 = (RuleCall)cLineEndsAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Assignment cLinesAssignment_2_0 = (Assignment)cGroup_2.eContents().get(0);
		private final RuleCall cLinesLineParserRuleCall_2_0_0 = (RuleCall)cLinesAssignment_2_0.eContents().get(0);
		private final Assignment cLineEndsAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cLineEndsLineEndParserRuleCall_2_1_0 = (RuleCall)cLineEndsAssignment_2_1.eContents().get(0);
		private final Assignment cLinesAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cLinesLineParserRuleCall_3_0 = (RuleCall)cLinesAssignment_3.eContents().get(0);
		
		////Rules
		//Program:
		//	{Program} lineEnds+=LineEnd* (lines+=Line lineEnds+=LineEnd+)* lines+=Line?;
		@Override public ParserRule getRule() { return rule; }
		
		//{Program} lineEnds+=LineEnd* (lines+=Line lineEnds+=LineEnd+)* lines+=Line?
		public Group getGroup() { return cGroup; }
		
		//{Program}
		public Action getProgramAction_0() { return cProgramAction_0; }
		
		//lineEnds+=LineEnd*
		public Assignment getLineEndsAssignment_1() { return cLineEndsAssignment_1; }
		
		//LineEnd
		public RuleCall getLineEndsLineEndParserRuleCall_1_0() { return cLineEndsLineEndParserRuleCall_1_0; }
		
		//(lines+=Line lineEnds+=LineEnd+)*
		public Group getGroup_2() { return cGroup_2; }
		
		//lines+=Line
		public Assignment getLinesAssignment_2_0() { return cLinesAssignment_2_0; }
		
		//Line
		public RuleCall getLinesLineParserRuleCall_2_0_0() { return cLinesLineParserRuleCall_2_0_0; }
		
		//lineEnds+=LineEnd+
		public Assignment getLineEndsAssignment_2_1() { return cLineEndsAssignment_2_1; }
		
		//LineEnd
		public RuleCall getLineEndsLineEndParserRuleCall_2_1_0() { return cLineEndsLineEndParserRuleCall_2_1_0; }
		
		//lines+=Line?
		public Assignment getLinesAssignment_3() { return cLinesAssignment_3; }
		
		//Line
		public RuleCall getLinesLineParserRuleCall_3_0() { return cLinesLineParserRuleCall_3_0; }
	}
	public class LineElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.team38.assembly.LC2200.Line");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cInstructionParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cDirectiveParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Line:
		//	Instruction | Directive;
		@Override public ParserRule getRule() { return rule; }
		
		//Instruction | Directive
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Instruction
		public RuleCall getInstructionParserRuleCall_0() { return cInstructionParserRuleCall_0; }
		
		//Directive
		public RuleCall getDirectiveParserRuleCall_1() { return cDirectiveParserRuleCall_1; }
	}
	public class InstructionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.team38.assembly.LC2200.Instruction");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cLabelAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cLabelLabelBegParserRuleCall_0_0 = (RuleCall)cLabelAssignment_0.eContents().get(0);
		private final Assignment cInstructionAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Alternatives cInstructionAlternatives_1_0 = (Alternatives)cInstructionAssignment_1.eContents().get(0);
		private final RuleCall cInstructionRInstructionParserRuleCall_1_0_0 = (RuleCall)cInstructionAlternatives_1_0.eContents().get(0);
		private final RuleCall cInstructionIInstructionParserRuleCall_1_0_1 = (RuleCall)cInstructionAlternatives_1_0.eContents().get(1);
		private final RuleCall cInstructionJInstructionParserRuleCall_1_0_2 = (RuleCall)cInstructionAlternatives_1_0.eContents().get(2);
		private final RuleCall cInstructionOInstructionParserRuleCall_1_0_3 = (RuleCall)cInstructionAlternatives_1_0.eContents().get(3);
		
		//Instruction:
		//	label=LabelBeg? instruction=(RInstruction | IInstruction | JInstruction | OInstruction);
		@Override public ParserRule getRule() { return rule; }
		
		//label=LabelBeg? instruction=(RInstruction | IInstruction | JInstruction | OInstruction)
		public Group getGroup() { return cGroup; }
		
		//label=LabelBeg?
		public Assignment getLabelAssignment_0() { return cLabelAssignment_0; }
		
		//LabelBeg
		public RuleCall getLabelLabelBegParserRuleCall_0_0() { return cLabelLabelBegParserRuleCall_0_0; }
		
		//instruction=(RInstruction | IInstruction | JInstruction | OInstruction)
		public Assignment getInstructionAssignment_1() { return cInstructionAssignment_1; }
		
		//(RInstruction | IInstruction | JInstruction | OInstruction)
		public Alternatives getInstructionAlternatives_1_0() { return cInstructionAlternatives_1_0; }
		
		//RInstruction
		public RuleCall getInstructionRInstructionParserRuleCall_1_0_0() { return cInstructionRInstructionParserRuleCall_1_0_0; }
		
		//IInstruction
		public RuleCall getInstructionIInstructionParserRuleCall_1_0_1() { return cInstructionIInstructionParserRuleCall_1_0_1; }
		
		//JInstruction
		public RuleCall getInstructionJInstructionParserRuleCall_1_0_2() { return cInstructionJInstructionParserRuleCall_1_0_2; }
		
		//OInstruction
		public RuleCall getInstructionOInstructionParserRuleCall_1_0_3() { return cInstructionOInstructionParserRuleCall_1_0_3; }
	}
	public class DirectiveElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.team38.assembly.LC2200.Directive");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cLabelAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cLabelLabelBegParserRuleCall_0_0 = (RuleCall)cLabelAssignment_0.eContents().get(0);
		private final Assignment cDirectiveAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Alternatives cDirectiveAlternatives_1_0 = (Alternatives)cDirectiveAssignment_1.eContents().get(0);
		private final RuleCall cDirectiveNOOPDirectiveParserRuleCall_1_0_0 = (RuleCall)cDirectiveAlternatives_1_0.eContents().get(0);
		private final RuleCall cDirectiveWordDirectiveParserRuleCall_1_0_1 = (RuleCall)cDirectiveAlternatives_1_0.eContents().get(1);
		private final RuleCall cDirectiveLADirectiveParserRuleCall_1_0_2 = (RuleCall)cDirectiveAlternatives_1_0.eContents().get(2);
		
		//Directive:
		//	label=LabelBeg? directive=(NOOPDirective | WordDirective | LADirective);
		@Override public ParserRule getRule() { return rule; }
		
		//label=LabelBeg? directive=(NOOPDirective | WordDirective | LADirective)
		public Group getGroup() { return cGroup; }
		
		//label=LabelBeg?
		public Assignment getLabelAssignment_0() { return cLabelAssignment_0; }
		
		//LabelBeg
		public RuleCall getLabelLabelBegParserRuleCall_0_0() { return cLabelLabelBegParserRuleCall_0_0; }
		
		//directive=(NOOPDirective | WordDirective | LADirective)
		public Assignment getDirectiveAssignment_1() { return cDirectiveAssignment_1; }
		
		//(NOOPDirective | WordDirective | LADirective)
		public Alternatives getDirectiveAlternatives_1_0() { return cDirectiveAlternatives_1_0; }
		
		//NOOPDirective
		public RuleCall getDirectiveNOOPDirectiveParserRuleCall_1_0_0() { return cDirectiveNOOPDirectiveParserRuleCall_1_0_0; }
		
		//WordDirective
		public RuleCall getDirectiveWordDirectiveParserRuleCall_1_0_1() { return cDirectiveWordDirectiveParserRuleCall_1_0_1; }
		
		//LADirective
		public RuleCall getDirectiveLADirectiveParserRuleCall_1_0_2() { return cDirectiveLADirectiveParserRuleCall_1_0_2; }
	}
	public class RInstructionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.team38.assembly.LC2200.RInstruction");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cR_opcodeAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cR_opcodeRInstructionTransParserRuleCall_0_0 = (RuleCall)cR_opcodeAssignment_0.eContents().get(0);
		private final Assignment cReg1Assignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cReg1RegTransParserRuleCall_1_0 = (RuleCall)cReg1Assignment_1.eContents().get(0);
		private final RuleCall cCOMMATerminalRuleCall_2 = (RuleCall)cGroup.eContents().get(2);
		private final Assignment cReg2Assignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cReg2RegTransParserRuleCall_3_0 = (RuleCall)cReg2Assignment_3.eContents().get(0);
		private final RuleCall cCOMMATerminalRuleCall_4 = (RuleCall)cGroup.eContents().get(4);
		private final Assignment cReg3Assignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cReg3RegTransParserRuleCall_5_0 = (RuleCall)cReg3Assignment_5.eContents().get(0);
		
		//RInstruction:
		//	r_opcode=RInstructionTrans reg1=RegTrans COMMA reg2=RegTrans COMMA reg3=RegTrans;
		@Override public ParserRule getRule() { return rule; }
		
		//r_opcode=RInstructionTrans reg1=RegTrans COMMA reg2=RegTrans COMMA reg3=RegTrans
		public Group getGroup() { return cGroup; }
		
		//r_opcode=RInstructionTrans
		public Assignment getR_opcodeAssignment_0() { return cR_opcodeAssignment_0; }
		
		//RInstructionTrans
		public RuleCall getR_opcodeRInstructionTransParserRuleCall_0_0() { return cR_opcodeRInstructionTransParserRuleCall_0_0; }
		
		//reg1=RegTrans
		public Assignment getReg1Assignment_1() { return cReg1Assignment_1; }
		
		//RegTrans
		public RuleCall getReg1RegTransParserRuleCall_1_0() { return cReg1RegTransParserRuleCall_1_0; }
		
		//COMMA
		public RuleCall getCOMMATerminalRuleCall_2() { return cCOMMATerminalRuleCall_2; }
		
		//reg2=RegTrans
		public Assignment getReg2Assignment_3() { return cReg2Assignment_3; }
		
		//RegTrans
		public RuleCall getReg2RegTransParserRuleCall_3_0() { return cReg2RegTransParserRuleCall_3_0; }
		
		//COMMA
		public RuleCall getCOMMATerminalRuleCall_4() { return cCOMMATerminalRuleCall_4; }
		
		//reg3=RegTrans
		public Assignment getReg3Assignment_5() { return cReg3Assignment_5; }
		
		//RegTrans
		public RuleCall getReg3RegTransParserRuleCall_5_0() { return cReg3RegTransParserRuleCall_5_0; }
	}
	public class IInstructionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.team38.assembly.LC2200.IInstruction");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Assignment cI_opcodeAssignment_0_0 = (Assignment)cGroup_0.eContents().get(0);
		private final RuleCall cI_opcodeIInstructionImmTransParserRuleCall_0_0_0 = (RuleCall)cI_opcodeAssignment_0_0.eContents().get(0);
		private final Assignment cReg1Assignment_0_1 = (Assignment)cGroup_0.eContents().get(1);
		private final RuleCall cReg1RegTransParserRuleCall_0_1_0 = (RuleCall)cReg1Assignment_0_1.eContents().get(0);
		private final RuleCall cCOMMATerminalRuleCall_0_2 = (RuleCall)cGroup_0.eContents().get(2);
		private final Assignment cReg2Assignment_0_3 = (Assignment)cGroup_0.eContents().get(3);
		private final RuleCall cReg2RegTransParserRuleCall_0_3_0 = (RuleCall)cReg2Assignment_0_3.eContents().get(0);
		private final RuleCall cCOMMATerminalRuleCall_0_4 = (RuleCall)cGroup_0.eContents().get(4);
		private final Assignment cImmAssignment_0_5 = (Assignment)cGroup_0.eContents().get(5);
		private final RuleCall cImmIMMEDIATETerminalRuleCall_0_5_0 = (RuleCall)cImmAssignment_0_5.eContents().get(0);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Assignment cI_opcodeAssignment_1_0 = (Assignment)cGroup_1.eContents().get(0);
		private final RuleCall cI_opcodeIInstructionOffsetTransParserRuleCall_1_0_0 = (RuleCall)cI_opcodeAssignment_1_0.eContents().get(0);
		private final Assignment cReg1Assignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cReg1RegTransParserRuleCall_1_1_0 = (RuleCall)cReg1Assignment_1_1.eContents().get(0);
		private final RuleCall cCOMMATerminalRuleCall_1_2 = (RuleCall)cGroup_1.eContents().get(2);
		private final Assignment cImmAssignment_1_3 = (Assignment)cGroup_1.eContents().get(3);
		private final RuleCall cImmIMMEDIATETerminalRuleCall_1_3_0 = (RuleCall)cImmAssignment_1_3.eContents().get(0);
		private final RuleCall cLPARENTerminalRuleCall_1_4 = (RuleCall)cGroup_1.eContents().get(4);
		private final Assignment cReg2Assignment_1_5 = (Assignment)cGroup_1.eContents().get(5);
		private final RuleCall cReg2RegTransParserRuleCall_1_5_0 = (RuleCall)cReg2Assignment_1_5.eContents().get(0);
		private final RuleCall cRPARENTerminalRuleCall_1_6 = (RuleCall)cGroup_1.eContents().get(6);
		private final Group cGroup_2 = (Group)cAlternatives.eContents().get(2);
		private final Assignment cI_opcodeAssignment_2_0 = (Assignment)cGroup_2.eContents().get(0);
		private final RuleCall cI_opcodeIInstructionLabelTransParserRuleCall_2_0_0 = (RuleCall)cI_opcodeAssignment_2_0.eContents().get(0);
		private final Assignment cReg1Assignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cReg1RegTransParserRuleCall_2_1_0 = (RuleCall)cReg1Assignment_2_1.eContents().get(0);
		private final RuleCall cCOMMATerminalRuleCall_2_2 = (RuleCall)cGroup_2.eContents().get(2);
		private final Assignment cReg2Assignment_2_3 = (Assignment)cGroup_2.eContents().get(3);
		private final RuleCall cReg2RegTransParserRuleCall_2_3_0 = (RuleCall)cReg2Assignment_2_3.eContents().get(0);
		private final RuleCall cCOMMATerminalRuleCall_2_4 = (RuleCall)cGroup_2.eContents().get(4);
		private final Assignment cLabelAssignment_2_5 = (Assignment)cGroup_2.eContents().get(5);
		private final RuleCall cLabelLabelEndParserRuleCall_2_5_0 = (RuleCall)cLabelAssignment_2_5.eContents().get(0);
		
		//IInstruction:
		//	i_opcode=IInstructionImmTrans reg1=RegTrans COMMA reg2=RegTrans COMMA imm=IMMEDIATE |
		//	i_opcode=IInstructionOffsetTrans reg1=RegTrans COMMA imm=IMMEDIATE LPAREN reg2=RegTrans RPAREN |
		//	i_opcode=IInstructionLabelTrans reg1=RegTrans COMMA reg2=RegTrans COMMA label=LabelEnd;
		@Override public ParserRule getRule() { return rule; }
		
		//i_opcode=IInstructionImmTrans reg1=RegTrans COMMA reg2=RegTrans COMMA imm=IMMEDIATE | i_opcode=IInstructionOffsetTrans
		//reg1=RegTrans COMMA imm=IMMEDIATE LPAREN reg2=RegTrans RPAREN | i_opcode=IInstructionLabelTrans reg1=RegTrans COMMA
		//reg2=RegTrans COMMA label=LabelEnd
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//i_opcode=IInstructionImmTrans reg1=RegTrans COMMA reg2=RegTrans COMMA imm=IMMEDIATE
		public Group getGroup_0() { return cGroup_0; }
		
		//i_opcode=IInstructionImmTrans
		public Assignment getI_opcodeAssignment_0_0() { return cI_opcodeAssignment_0_0; }
		
		//IInstructionImmTrans
		public RuleCall getI_opcodeIInstructionImmTransParserRuleCall_0_0_0() { return cI_opcodeIInstructionImmTransParserRuleCall_0_0_0; }
		
		//reg1=RegTrans
		public Assignment getReg1Assignment_0_1() { return cReg1Assignment_0_1; }
		
		//RegTrans
		public RuleCall getReg1RegTransParserRuleCall_0_1_0() { return cReg1RegTransParserRuleCall_0_1_0; }
		
		//COMMA
		public RuleCall getCOMMATerminalRuleCall_0_2() { return cCOMMATerminalRuleCall_0_2; }
		
		//reg2=RegTrans
		public Assignment getReg2Assignment_0_3() { return cReg2Assignment_0_3; }
		
		//RegTrans
		public RuleCall getReg2RegTransParserRuleCall_0_3_0() { return cReg2RegTransParserRuleCall_0_3_0; }
		
		//COMMA
		public RuleCall getCOMMATerminalRuleCall_0_4() { return cCOMMATerminalRuleCall_0_4; }
		
		//imm=IMMEDIATE
		public Assignment getImmAssignment_0_5() { return cImmAssignment_0_5; }
		
		//IMMEDIATE
		public RuleCall getImmIMMEDIATETerminalRuleCall_0_5_0() { return cImmIMMEDIATETerminalRuleCall_0_5_0; }
		
		//i_opcode=IInstructionOffsetTrans reg1=RegTrans COMMA imm=IMMEDIATE LPAREN reg2=RegTrans RPAREN
		public Group getGroup_1() { return cGroup_1; }
		
		//i_opcode=IInstructionOffsetTrans
		public Assignment getI_opcodeAssignment_1_0() { return cI_opcodeAssignment_1_0; }
		
		//IInstructionOffsetTrans
		public RuleCall getI_opcodeIInstructionOffsetTransParserRuleCall_1_0_0() { return cI_opcodeIInstructionOffsetTransParserRuleCall_1_0_0; }
		
		//reg1=RegTrans
		public Assignment getReg1Assignment_1_1() { return cReg1Assignment_1_1; }
		
		//RegTrans
		public RuleCall getReg1RegTransParserRuleCall_1_1_0() { return cReg1RegTransParserRuleCall_1_1_0; }
		
		//COMMA
		public RuleCall getCOMMATerminalRuleCall_1_2() { return cCOMMATerminalRuleCall_1_2; }
		
		//imm=IMMEDIATE
		public Assignment getImmAssignment_1_3() { return cImmAssignment_1_3; }
		
		//IMMEDIATE
		public RuleCall getImmIMMEDIATETerminalRuleCall_1_3_0() { return cImmIMMEDIATETerminalRuleCall_1_3_0; }
		
		//LPAREN
		public RuleCall getLPARENTerminalRuleCall_1_4() { return cLPARENTerminalRuleCall_1_4; }
		
		//reg2=RegTrans
		public Assignment getReg2Assignment_1_5() { return cReg2Assignment_1_5; }
		
		//RegTrans
		public RuleCall getReg2RegTransParserRuleCall_1_5_0() { return cReg2RegTransParserRuleCall_1_5_0; }
		
		//RPAREN
		public RuleCall getRPARENTerminalRuleCall_1_6() { return cRPARENTerminalRuleCall_1_6; }
		
		//i_opcode=IInstructionLabelTrans reg1=RegTrans COMMA reg2=RegTrans COMMA label=LabelEnd
		public Group getGroup_2() { return cGroup_2; }
		
		//i_opcode=IInstructionLabelTrans
		public Assignment getI_opcodeAssignment_2_0() { return cI_opcodeAssignment_2_0; }
		
		//IInstructionLabelTrans
		public RuleCall getI_opcodeIInstructionLabelTransParserRuleCall_2_0_0() { return cI_opcodeIInstructionLabelTransParserRuleCall_2_0_0; }
		
		//reg1=RegTrans
		public Assignment getReg1Assignment_2_1() { return cReg1Assignment_2_1; }
		
		//RegTrans
		public RuleCall getReg1RegTransParserRuleCall_2_1_0() { return cReg1RegTransParserRuleCall_2_1_0; }
		
		//COMMA
		public RuleCall getCOMMATerminalRuleCall_2_2() { return cCOMMATerminalRuleCall_2_2; }
		
		//reg2=RegTrans
		public Assignment getReg2Assignment_2_3() { return cReg2Assignment_2_3; }
		
		//RegTrans
		public RuleCall getReg2RegTransParserRuleCall_2_3_0() { return cReg2RegTransParserRuleCall_2_3_0; }
		
		//COMMA
		public RuleCall getCOMMATerminalRuleCall_2_4() { return cCOMMATerminalRuleCall_2_4; }
		
		//label=LabelEnd
		public Assignment getLabelAssignment_2_5() { return cLabelAssignment_2_5; }
		
		//LabelEnd
		public RuleCall getLabelLabelEndParserRuleCall_2_5_0() { return cLabelLabelEndParserRuleCall_2_5_0; }
	}
	public class JInstructionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.team38.assembly.LC2200.JInstruction");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cJ_opcodeAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cJ_opcodeJInstructionTransParserRuleCall_0_0 = (RuleCall)cJ_opcodeAssignment_0.eContents().get(0);
		private final Assignment cReg1Assignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cReg1RegTransParserRuleCall_1_0 = (RuleCall)cReg1Assignment_1.eContents().get(0);
		private final RuleCall cCOMMATerminalRuleCall_2 = (RuleCall)cGroup.eContents().get(2);
		private final Assignment cReg2Assignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cReg2RegTransParserRuleCall_3_0 = (RuleCall)cReg2Assignment_3.eContents().get(0);
		
		//JInstruction:
		//	j_opcode=JInstructionTrans reg1=RegTrans COMMA reg2=RegTrans;
		@Override public ParserRule getRule() { return rule; }
		
		//j_opcode=JInstructionTrans reg1=RegTrans COMMA reg2=RegTrans
		public Group getGroup() { return cGroup; }
		
		//j_opcode=JInstructionTrans
		public Assignment getJ_opcodeAssignment_0() { return cJ_opcodeAssignment_0; }
		
		//JInstructionTrans
		public RuleCall getJ_opcodeJInstructionTransParserRuleCall_0_0() { return cJ_opcodeJInstructionTransParserRuleCall_0_0; }
		
		//reg1=RegTrans
		public Assignment getReg1Assignment_1() { return cReg1Assignment_1; }
		
		//RegTrans
		public RuleCall getReg1RegTransParserRuleCall_1_0() { return cReg1RegTransParserRuleCall_1_0; }
		
		//COMMA
		public RuleCall getCOMMATerminalRuleCall_2() { return cCOMMATerminalRuleCall_2; }
		
		//reg2=RegTrans
		public Assignment getReg2Assignment_3() { return cReg2Assignment_3; }
		
		//RegTrans
		public RuleCall getReg2RegTransParserRuleCall_3_0() { return cReg2RegTransParserRuleCall_3_0; }
	}
	public class OInstructionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.team38.assembly.LC2200.OInstruction");
		private final Assignment cO_opcodeAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cO_opcodeOOPTerminalRuleCall_0 = (RuleCall)cO_opcodeAssignment.eContents().get(0);
		
		//OInstruction:
		//	o_opcode=OOP;
		@Override public ParserRule getRule() { return rule; }
		
		//o_opcode=OOP
		public Assignment getO_opcodeAssignment() { return cO_opcodeAssignment; }
		
		//OOP
		public RuleCall getO_opcodeOOPTerminalRuleCall_0() { return cO_opcodeOOPTerminalRuleCall_0; }
	}
	public class NOOPDirectiveElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.team38.assembly.LC2200.NOOPDirective");
		private final Assignment cN_dirAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cN_dirNOOPTerminalRuleCall_0 = (RuleCall)cN_dirAssignment.eContents().get(0);
		
		//NOOPDirective:
		//	n_dir=NOOP;
		@Override public ParserRule getRule() { return rule; }
		
		//n_dir=NOOP
		public Assignment getN_dirAssignment() { return cN_dirAssignment; }
		
		//NOOP
		public RuleCall getN_dirNOOPTerminalRuleCall_0() { return cN_dirNOOPTerminalRuleCall_0; }
	}
	public class WordDirectiveElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.team38.assembly.LC2200.WordDirective");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cW_dirAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cW_dirWordTransParserRuleCall_0_0 = (RuleCall)cW_dirAssignment_0.eContents().get(0);
		private final Assignment cImmAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cImmIMMEDIATETerminalRuleCall_1_0 = (RuleCall)cImmAssignment_1.eContents().get(0);
		
		//WordDirective:
		//	w_dir=WordTrans imm=IMMEDIATE;
		@Override public ParserRule getRule() { return rule; }
		
		//w_dir=WordTrans imm=IMMEDIATE
		public Group getGroup() { return cGroup; }
		
		//w_dir=WordTrans
		public Assignment getW_dirAssignment_0() { return cW_dirAssignment_0; }
		
		//WordTrans
		public RuleCall getW_dirWordTransParserRuleCall_0_0() { return cW_dirWordTransParserRuleCall_0_0; }
		
		//imm=IMMEDIATE
		public Assignment getImmAssignment_1() { return cImmAssignment_1; }
		
		//IMMEDIATE
		public RuleCall getImmIMMEDIATETerminalRuleCall_1_0() { return cImmIMMEDIATETerminalRuleCall_1_0; }
	}
	public class LADirectiveElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.team38.assembly.LC2200.LADirective");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cLa_dirAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cLa_dirLATransParserRuleCall_0_0 = (RuleCall)cLa_dirAssignment_0.eContents().get(0);
		private final Assignment cRegAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cRegRegTransParserRuleCall_1_0 = (RuleCall)cRegAssignment_1.eContents().get(0);
		private final RuleCall cCOMMATerminalRuleCall_2 = (RuleCall)cGroup.eContents().get(2);
		private final Assignment cLabelAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cLabelLabelEndParserRuleCall_3_0 = (RuleCall)cLabelAssignment_3.eContents().get(0);
		
		//LADirective:
		//	la_dir=LATrans reg=RegTrans COMMA label=LabelEnd;
		@Override public ParserRule getRule() { return rule; }
		
		//la_dir=LATrans reg=RegTrans COMMA label=LabelEnd
		public Group getGroup() { return cGroup; }
		
		//la_dir=LATrans
		public Assignment getLa_dirAssignment_0() { return cLa_dirAssignment_0; }
		
		//LATrans
		public RuleCall getLa_dirLATransParserRuleCall_0_0() { return cLa_dirLATransParserRuleCall_0_0; }
		
		//reg=RegTrans
		public Assignment getRegAssignment_1() { return cRegAssignment_1; }
		
		//RegTrans
		public RuleCall getRegRegTransParserRuleCall_1_0() { return cRegRegTransParserRuleCall_1_0; }
		
		//COMMA
		public RuleCall getCOMMATerminalRuleCall_2() { return cCOMMATerminalRuleCall_2; }
		
		//label=LabelEnd
		public Assignment getLabelAssignment_3() { return cLabelAssignment_3; }
		
		//LabelEnd
		public RuleCall getLabelLabelEndParserRuleCall_3_0() { return cLabelLabelEndParserRuleCall_3_0; }
	}
	public class RInstructionTransElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.team38.assembly.LC2200.RInstructionTrans");
		private final Assignment cR_opcodeAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cR_opcodeROPTerminalRuleCall_0 = (RuleCall)cR_opcodeAssignment.eContents().get(0);
		
		////Transition Rules
		////Used for Syntax Coloring
		//RInstructionTrans:
		//	r_opcode=ROP;
		@Override public ParserRule getRule() { return rule; }
		
		//r_opcode=ROP
		public Assignment getR_opcodeAssignment() { return cR_opcodeAssignment; }
		
		//ROP
		public RuleCall getR_opcodeROPTerminalRuleCall_0() { return cR_opcodeROPTerminalRuleCall_0; }
	}
	public class IInstructionImmTransElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.team38.assembly.LC2200.IInstructionImmTrans");
		private final Assignment cI_opcodeAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cI_opcodeIOP_IMMTerminalRuleCall_0 = (RuleCall)cI_opcodeAssignment.eContents().get(0);
		
		//IInstructionImmTrans:
		//	i_opcode=IOP_IMM;
		@Override public ParserRule getRule() { return rule; }
		
		//i_opcode=IOP_IMM
		public Assignment getI_opcodeAssignment() { return cI_opcodeAssignment; }
		
		//IOP_IMM
		public RuleCall getI_opcodeIOP_IMMTerminalRuleCall_0() { return cI_opcodeIOP_IMMTerminalRuleCall_0; }
	}
	public class IInstructionOffsetTransElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.team38.assembly.LC2200.IInstructionOffsetTrans");
		private final Assignment cI_opcodeAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cI_opcodeIOP_OFFSETTerminalRuleCall_0 = (RuleCall)cI_opcodeAssignment.eContents().get(0);
		
		//IInstructionOffsetTrans:
		//	i_opcode=IOP_OFFSET;
		@Override public ParserRule getRule() { return rule; }
		
		//i_opcode=IOP_OFFSET
		public Assignment getI_opcodeAssignment() { return cI_opcodeAssignment; }
		
		//IOP_OFFSET
		public RuleCall getI_opcodeIOP_OFFSETTerminalRuleCall_0() { return cI_opcodeIOP_OFFSETTerminalRuleCall_0; }
	}
	public class IInstructionLabelTransElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.team38.assembly.LC2200.IInstructionLabelTrans");
		private final Assignment cI_opcodeAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cI_opcodeIOP_LABELTerminalRuleCall_0 = (RuleCall)cI_opcodeAssignment.eContents().get(0);
		
		//IInstructionLabelTrans:
		//	i_opcode=IOP_LABEL;
		@Override public ParserRule getRule() { return rule; }
		
		//i_opcode=IOP_LABEL
		public Assignment getI_opcodeAssignment() { return cI_opcodeAssignment; }
		
		//IOP_LABEL
		public RuleCall getI_opcodeIOP_LABELTerminalRuleCall_0() { return cI_opcodeIOP_LABELTerminalRuleCall_0; }
	}
	public class JInstructionTransElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.team38.assembly.LC2200.JInstructionTrans");
		private final Assignment cJ_opcodeAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cJ_opcodeJOPTerminalRuleCall_0 = (RuleCall)cJ_opcodeAssignment.eContents().get(0);
		
		//JInstructionTrans:
		//	j_opcode=JOP;
		@Override public ParserRule getRule() { return rule; }
		
		//j_opcode=JOP
		public Assignment getJ_opcodeAssignment() { return cJ_opcodeAssignment; }
		
		//JOP
		public RuleCall getJ_opcodeJOPTerminalRuleCall_0() { return cJ_opcodeJOPTerminalRuleCall_0; }
	}
	public class WordTransElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.team38.assembly.LC2200.WordTrans");
		private final Assignment cWordAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cWordWORDTerminalRuleCall_0 = (RuleCall)cWordAssignment.eContents().get(0);
		
		//WordTrans:
		//	word=WORD;
		@Override public ParserRule getRule() { return rule; }
		
		//word=WORD
		public Assignment getWordAssignment() { return cWordAssignment; }
		
		//WORD
		public RuleCall getWordWORDTerminalRuleCall_0() { return cWordWORDTerminalRuleCall_0; }
	}
	public class LATransElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.team38.assembly.LC2200.LATrans");
		private final Assignment cLaAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cLaLATerminalRuleCall_0 = (RuleCall)cLaAssignment.eContents().get(0);
		
		//LATrans:
		//	la=LA;
		@Override public ParserRule getRule() { return rule; }
		
		//la=LA
		public Assignment getLaAssignment() { return cLaAssignment; }
		
		//LA
		public RuleCall getLaLATerminalRuleCall_0() { return cLaLATerminalRuleCall_0; }
	}
	public class CommentTransElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.team38.assembly.LC2200.CommentTrans");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cCommentTransAction_0 = (Action)cGroup.eContents().get(0);
		private final RuleCall cCOMMENTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//CommentTrans:
		//	{CommentTrans} COMMENT;
		@Override public ParserRule getRule() { return rule; }
		
		//{CommentTrans} COMMENT
		public Group getGroup() { return cGroup; }
		
		//{CommentTrans}
		public Action getCommentTransAction_0() { return cCommentTransAction_0; }
		
		//COMMENT
		public RuleCall getCOMMENTTerminalRuleCall_1() { return cCOMMENTTerminalRuleCall_1; }
	}
	public class LineEndElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.team38.assembly.LC2200.LineEnd");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cLineEndAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cCommentAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cCommentCommentTransParserRuleCall_1_0 = (RuleCall)cCommentAssignment_1.eContents().get(0);
		private final RuleCall cNEWLINETerminalRuleCall_2 = (RuleCall)cGroup.eContents().get(2);
		
		//LineEnd:
		//	{LineEnd} comment=CommentTrans? NEWLINE;
		@Override public ParserRule getRule() { return rule; }
		
		//{LineEnd} comment=CommentTrans? NEWLINE
		public Group getGroup() { return cGroup; }
		
		//{LineEnd}
		public Action getLineEndAction_0() { return cLineEndAction_0; }
		
		//comment=CommentTrans?
		public Assignment getCommentAssignment_1() { return cCommentAssignment_1; }
		
		//CommentTrans
		public RuleCall getCommentCommentTransParserRuleCall_1_0() { return cCommentCommentTransParserRuleCall_1_0; }
		
		//NEWLINE
		public RuleCall getNEWLINETerminalRuleCall_2() { return cNEWLINETerminalRuleCall_2; }
	}
	public class RegTransElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.team38.assembly.LC2200.RegTrans");
		private final Assignment cRegAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cRegREGTerminalRuleCall_0 = (RuleCall)cRegAssignment.eContents().get(0);
		
		//RegTrans:
		//	reg=REG;
		@Override public ParserRule getRule() { return rule; }
		
		//reg=REG
		public Assignment getRegAssignment() { return cRegAssignment; }
		
		//REG
		public RuleCall getRegREGTerminalRuleCall_0() { return cRegREGTerminalRuleCall_0; }
	}
	public class LabelBegElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.team38.assembly.LC2200.LabelBeg");
		private final Assignment cLabelAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cLabelLABELTerminalRuleCall_0 = (RuleCall)cLabelAssignment.eContents().get(0);
		
		//LabelBeg:
		//	label=LABEL;
		@Override public ParserRule getRule() { return rule; }
		
		//label=LABEL
		public Assignment getLabelAssignment() { return cLabelAssignment; }
		
		//LABEL
		public RuleCall getLabelLABELTerminalRuleCall_0() { return cLabelLABELTerminalRuleCall_0; }
	}
	public class LabelEndElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.team38.assembly.LC2200.LabelEnd");
		private final Assignment cLabelAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cLabelLABEL_IMMTerminalRuleCall_0 = (RuleCall)cLabelAssignment.eContents().get(0);
		
		//LabelEnd:
		//	label=LABEL_IMM;
		@Override public ParserRule getRule() { return rule; }
		
		//label=LABEL_IMM
		public Assignment getLabelAssignment() { return cLabelAssignment; }
		
		//LABEL_IMM
		public RuleCall getLabelLABEL_IMMTerminalRuleCall_0() { return cLabelLABEL_IMMTerminalRuleCall_0; }
	}
	
	
	private final ProgramElements pProgram;
	private final LineElements pLine;
	private final InstructionElements pInstruction;
	private final DirectiveElements pDirective;
	private final RInstructionElements pRInstruction;
	private final IInstructionElements pIInstruction;
	private final JInstructionElements pJInstruction;
	private final OInstructionElements pOInstruction;
	private final NOOPDirectiveElements pNOOPDirective;
	private final WordDirectiveElements pWordDirective;
	private final LADirectiveElements pLADirective;
	private final RInstructionTransElements pRInstructionTrans;
	private final IInstructionImmTransElements pIInstructionImmTrans;
	private final IInstructionOffsetTransElements pIInstructionOffsetTrans;
	private final IInstructionLabelTransElements pIInstructionLabelTrans;
	private final JInstructionTransElements pJInstructionTrans;
	private final WordTransElements pWordTrans;
	private final LATransElements pLATrans;
	private final CommentTransElements pCommentTrans;
	private final LineEndElements pLineEnd;
	private final RegTransElements pRegTrans;
	private final LabelBegElements pLabelBeg;
	private final LabelEndElements pLabelEnd;
	private final TerminalRule tWS;
	private final TerminalRule tLA;
	private final TerminalRule tWORD;
	private final TerminalRule tOOP;
	private final TerminalRule tNOOP;
	private final TerminalRule tJOP;
	private final TerminalRule tROP;
	private final TerminalRule tIOP_IMM;
	private final TerminalRule tIOP_OFFSET;
	private final TerminalRule tIOP_LABEL;
	private final TerminalRule tLPAREN;
	private final TerminalRule tRPAREN;
	private final TerminalRule tCOMMA;
	private final TerminalRule tCOMMENT;
	private final TerminalRule tNEWLINE;
	private final TerminalRule tREG;
	private final TerminalRule tIMMEDIATE;
	private final TerminalRule tLABEL_IMM;
	private final TerminalRule tLABEL;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public LC2200GrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pProgram = new ProgramElements();
		this.pLine = new LineElements();
		this.pInstruction = new InstructionElements();
		this.pDirective = new DirectiveElements();
		this.pRInstruction = new RInstructionElements();
		this.pIInstruction = new IInstructionElements();
		this.pJInstruction = new JInstructionElements();
		this.pOInstruction = new OInstructionElements();
		this.pNOOPDirective = new NOOPDirectiveElements();
		this.pWordDirective = new WordDirectiveElements();
		this.pLADirective = new LADirectiveElements();
		this.pRInstructionTrans = new RInstructionTransElements();
		this.pIInstructionImmTrans = new IInstructionImmTransElements();
		this.pIInstructionOffsetTrans = new IInstructionOffsetTransElements();
		this.pIInstructionLabelTrans = new IInstructionLabelTransElements();
		this.pJInstructionTrans = new JInstructionTransElements();
		this.pWordTrans = new WordTransElements();
		this.pLATrans = new LATransElements();
		this.pCommentTrans = new CommentTransElements();
		this.pLineEnd = new LineEndElements();
		this.pRegTrans = new RegTransElements();
		this.pLabelBeg = new LabelBegElements();
		this.pLabelEnd = new LabelEndElements();
		this.tWS = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.team38.assembly.LC2200.WS");
		this.tLA = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.team38.assembly.LC2200.LA");
		this.tWORD = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.team38.assembly.LC2200.WORD");
		this.tOOP = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.team38.assembly.LC2200.OOP");
		this.tNOOP = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.team38.assembly.LC2200.NOOP");
		this.tJOP = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.team38.assembly.LC2200.JOP");
		this.tROP = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.team38.assembly.LC2200.ROP");
		this.tIOP_IMM = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.team38.assembly.LC2200.IOP_IMM");
		this.tIOP_OFFSET = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.team38.assembly.LC2200.IOP_OFFSET");
		this.tIOP_LABEL = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.team38.assembly.LC2200.IOP_LABEL");
		this.tLPAREN = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.team38.assembly.LC2200.LPAREN");
		this.tRPAREN = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.team38.assembly.LC2200.RPAREN");
		this.tCOMMA = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.team38.assembly.LC2200.COMMA");
		this.tCOMMENT = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.team38.assembly.LC2200.COMMENT");
		this.tNEWLINE = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.team38.assembly.LC2200.NEWLINE");
		this.tREG = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.team38.assembly.LC2200.REG");
		this.tIMMEDIATE = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.team38.assembly.LC2200.IMMEDIATE");
		this.tLABEL_IMM = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.team38.assembly.LC2200.LABEL_IMM");
		this.tLABEL = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.team38.assembly.LC2200.LABEL");
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.team38.assembly.LC2200".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	////Rules
	//Program:
	//	{Program} lineEnds+=LineEnd* (lines+=Line lineEnds+=LineEnd+)* lines+=Line?;
	public ProgramElements getProgramAccess() {
		return pProgram;
	}
	
	public ParserRule getProgramRule() {
		return getProgramAccess().getRule();
	}
	
	//Line:
	//	Instruction | Directive;
	public LineElements getLineAccess() {
		return pLine;
	}
	
	public ParserRule getLineRule() {
		return getLineAccess().getRule();
	}
	
	//Instruction:
	//	label=LabelBeg? instruction=(RInstruction | IInstruction | JInstruction | OInstruction);
	public InstructionElements getInstructionAccess() {
		return pInstruction;
	}
	
	public ParserRule getInstructionRule() {
		return getInstructionAccess().getRule();
	}
	
	//Directive:
	//	label=LabelBeg? directive=(NOOPDirective | WordDirective | LADirective);
	public DirectiveElements getDirectiveAccess() {
		return pDirective;
	}
	
	public ParserRule getDirectiveRule() {
		return getDirectiveAccess().getRule();
	}
	
	//RInstruction:
	//	r_opcode=RInstructionTrans reg1=RegTrans COMMA reg2=RegTrans COMMA reg3=RegTrans;
	public RInstructionElements getRInstructionAccess() {
		return pRInstruction;
	}
	
	public ParserRule getRInstructionRule() {
		return getRInstructionAccess().getRule();
	}
	
	//IInstruction:
	//	i_opcode=IInstructionImmTrans reg1=RegTrans COMMA reg2=RegTrans COMMA imm=IMMEDIATE |
	//	i_opcode=IInstructionOffsetTrans reg1=RegTrans COMMA imm=IMMEDIATE LPAREN reg2=RegTrans RPAREN |
	//	i_opcode=IInstructionLabelTrans reg1=RegTrans COMMA reg2=RegTrans COMMA label=LabelEnd;
	public IInstructionElements getIInstructionAccess() {
		return pIInstruction;
	}
	
	public ParserRule getIInstructionRule() {
		return getIInstructionAccess().getRule();
	}
	
	//JInstruction:
	//	j_opcode=JInstructionTrans reg1=RegTrans COMMA reg2=RegTrans;
	public JInstructionElements getJInstructionAccess() {
		return pJInstruction;
	}
	
	public ParserRule getJInstructionRule() {
		return getJInstructionAccess().getRule();
	}
	
	//OInstruction:
	//	o_opcode=OOP;
	public OInstructionElements getOInstructionAccess() {
		return pOInstruction;
	}
	
	public ParserRule getOInstructionRule() {
		return getOInstructionAccess().getRule();
	}
	
	//NOOPDirective:
	//	n_dir=NOOP;
	public NOOPDirectiveElements getNOOPDirectiveAccess() {
		return pNOOPDirective;
	}
	
	public ParserRule getNOOPDirectiveRule() {
		return getNOOPDirectiveAccess().getRule();
	}
	
	//WordDirective:
	//	w_dir=WordTrans imm=IMMEDIATE;
	public WordDirectiveElements getWordDirectiveAccess() {
		return pWordDirective;
	}
	
	public ParserRule getWordDirectiveRule() {
		return getWordDirectiveAccess().getRule();
	}
	
	//LADirective:
	//	la_dir=LATrans reg=RegTrans COMMA label=LabelEnd;
	public LADirectiveElements getLADirectiveAccess() {
		return pLADirective;
	}
	
	public ParserRule getLADirectiveRule() {
		return getLADirectiveAccess().getRule();
	}
	
	////Transition Rules
	////Used for Syntax Coloring
	//RInstructionTrans:
	//	r_opcode=ROP;
	public RInstructionTransElements getRInstructionTransAccess() {
		return pRInstructionTrans;
	}
	
	public ParserRule getRInstructionTransRule() {
		return getRInstructionTransAccess().getRule();
	}
	
	//IInstructionImmTrans:
	//	i_opcode=IOP_IMM;
	public IInstructionImmTransElements getIInstructionImmTransAccess() {
		return pIInstructionImmTrans;
	}
	
	public ParserRule getIInstructionImmTransRule() {
		return getIInstructionImmTransAccess().getRule();
	}
	
	//IInstructionOffsetTrans:
	//	i_opcode=IOP_OFFSET;
	public IInstructionOffsetTransElements getIInstructionOffsetTransAccess() {
		return pIInstructionOffsetTrans;
	}
	
	public ParserRule getIInstructionOffsetTransRule() {
		return getIInstructionOffsetTransAccess().getRule();
	}
	
	//IInstructionLabelTrans:
	//	i_opcode=IOP_LABEL;
	public IInstructionLabelTransElements getIInstructionLabelTransAccess() {
		return pIInstructionLabelTrans;
	}
	
	public ParserRule getIInstructionLabelTransRule() {
		return getIInstructionLabelTransAccess().getRule();
	}
	
	//JInstructionTrans:
	//	j_opcode=JOP;
	public JInstructionTransElements getJInstructionTransAccess() {
		return pJInstructionTrans;
	}
	
	public ParserRule getJInstructionTransRule() {
		return getJInstructionTransAccess().getRule();
	}
	
	//WordTrans:
	//	word=WORD;
	public WordTransElements getWordTransAccess() {
		return pWordTrans;
	}
	
	public ParserRule getWordTransRule() {
		return getWordTransAccess().getRule();
	}
	
	//LATrans:
	//	la=LA;
	public LATransElements getLATransAccess() {
		return pLATrans;
	}
	
	public ParserRule getLATransRule() {
		return getLATransAccess().getRule();
	}
	
	//CommentTrans:
	//	{CommentTrans} COMMENT;
	public CommentTransElements getCommentTransAccess() {
		return pCommentTrans;
	}
	
	public ParserRule getCommentTransRule() {
		return getCommentTransAccess().getRule();
	}
	
	//LineEnd:
	//	{LineEnd} comment=CommentTrans? NEWLINE;
	public LineEndElements getLineEndAccess() {
		return pLineEnd;
	}
	
	public ParserRule getLineEndRule() {
		return getLineEndAccess().getRule();
	}
	
	//RegTrans:
	//	reg=REG;
	public RegTransElements getRegTransAccess() {
		return pRegTrans;
	}
	
	public ParserRule getRegTransRule() {
		return getRegTransAccess().getRule();
	}
	
	//LabelBeg:
	//	label=LABEL;
	public LabelBegElements getLabelBegAccess() {
		return pLabelBeg;
	}
	
	public ParserRule getLabelBegRule() {
		return getLabelBegAccess().getRule();
	}
	
	//LabelEnd:
	//	label=LABEL_IMM;
	public LabelEndElements getLabelEndAccess() {
		return pLabelEnd;
	}
	
	public ParserRule getLabelEndRule() {
		return getLabelEndAccess().getRule();
	}
	
	//terminal WS:
	//	' ' | '\t'+;
	public TerminalRule getWSRule() {
		return tWS;
	}
	
	//terminal LA:
	//	'la';
	public TerminalRule getLARule() {
		return tLA;
	}
	
	//terminal WORD:
	//	'.word';
	public TerminalRule getWORDRule() {
		return tWORD;
	}
	
	//terminal OOP:
	//	'halt' |
	//	'ei' |
	//	'di' |
	//	'reti';
	public TerminalRule getOOPRule() {
		return tOOP;
	}
	
	//terminal NOOP:
	//	'noop';
	public TerminalRule getNOOPRule() {
		return tNOOP;
	}
	
	//terminal JOP:
	//	'jalr';
	public TerminalRule getJOPRule() {
		return tJOP;
	}
	
	//terminal ROP:
	//	'add' |
	//	'nand';
	public TerminalRule getROPRule() {
		return tROP;
	}
	
	//terminal IOP_IMM:
	//	'addi';
	public TerminalRule getIOP_IMMRule() {
		return tIOP_IMM;
	}
	
	//terminal IOP_OFFSET:
	//	'lw' |
	//	'sw';
	public TerminalRule getIOP_OFFSETRule() {
		return tIOP_OFFSET;
	}
	
	//terminal IOP_LABEL:
	//	'beq';
	public TerminalRule getIOP_LABELRule() {
		return tIOP_LABEL;
	}
	
	//terminal LPAREN:
	//	'(';
	public TerminalRule getLPARENRule() {
		return tLPAREN;
	}
	
	//terminal RPAREN:
	//	')';
	public TerminalRule getRPARENRule() {
		return tRPAREN;
	}
	
	//terminal COMMA:
	//	',';
	public TerminalRule getCOMMARule() {
		return tCOMMA;
	}
	
	//terminal COMMENT:
	//	';' !('\n' | '\r')*;
	public TerminalRule getCOMMENTRule() {
		return tCOMMENT;
	}
	
	//terminal NEWLINE:
	//	' '* '\r'? '\n';
	public TerminalRule getNEWLINERule() {
		return tNEWLINE;
	}
	
	//terminal REG:
	//	'$zero' |
	//	'$at' |
	//	'$v0' |
	//	'$a0' |
	//	'$a1' |
	//	'$a2' |
	//	'$t0' |
	//	'$t1' |
	//	'$t2' |
	//	'$s0' |
	//	'$s1' |
	//	'$s2' |
	//	'$k0' |
	//	'$sp' |
	//	'$fp' |
	//	'$ra';
	public TerminalRule getREGRule() {
		return tREG;
	}
	
	//terminal IMMEDIATE:
	//	'0x' ('0'..'9' | ('a' | 'b' | 'c' | 'd' | 'e' | 'f'))+ | '-'? INT;
	public TerminalRule getIMMEDIATERule() {
		return tIMMEDIATE;
	}
	
	//terminal LABEL_IMM:
	//	('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getLABEL_IMMRule() {
		return tLABEL_IMM;
	}
	
	//terminal LABEL:
	//	LABEL_IMM ':';
	public TerminalRule getLABELRule() {
		return tLABEL;
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' | "'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/ *'->'* /';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
