/*
 * generated by Xtext 2.9.1
 */
package org.team38.assembly.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.junit4.IInjectorProvider;
import org.team38.assembly.ui.internal.AssemblyActivator;

public class LC2200UiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return AssemblyActivator.getInstance().getInjector("org.team38.assembly.LC2200");
	}

}
