/**
 * generated by Xtext 2.9.1
 */
package org.team38.assembly.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.team38.assembly.ui.AbstractLC2200UiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class LC2200UiModule extends AbstractLC2200UiModule {
  public LC2200UiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
