/**
 * generated by Xtext 2.9.1
 */
package org.team38.assembly.lC2200;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>IInstruction Offset Trans</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.team38.assembly.lC2200.IInstructionOffsetTrans#getI_opcode <em>Iopcode</em>}</li>
 * </ul>
 *
 * @see org.team38.assembly.lC2200.LC2200Package#getIInstructionOffsetTrans()
 * @model
 * @generated
 */
public interface IInstructionOffsetTrans extends EObject
{
  /**
   * Returns the value of the '<em><b>Iopcode</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Iopcode</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Iopcode</em>' attribute.
   * @see #setI_opcode(String)
   * @see org.team38.assembly.lC2200.LC2200Package#getIInstructionOffsetTrans_I_opcode()
   * @model
   * @generated
   */
  String getI_opcode();

  /**
   * Sets the value of the '{@link org.team38.assembly.lC2200.IInstructionOffsetTrans#getI_opcode <em>Iopcode</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Iopcode</em>' attribute.
   * @see #getI_opcode()
   * @generated
   */
  void setI_opcode(String value);

} // IInstructionOffsetTrans
