/**
 * generated by Xtext 2.9.2
 */
package org.team38.assembly.lC2200;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>LA Directive</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.team38.assembly.lC2200.LADirective#getLa_dir <em>La dir</em>}</li>
 *   <li>{@link org.team38.assembly.lC2200.LADirective#getReg <em>Reg</em>}</li>
 *   <li>{@link org.team38.assembly.lC2200.LADirective#getLabel <em>Label</em>}</li>
 * </ul>
 *
 * @see org.team38.assembly.lC2200.LC2200Package#getLADirective()
 * @model
 * @generated
 */
public interface LADirective extends EObject
{
  /**
   * Returns the value of the '<em><b>La dir</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>La dir</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>La dir</em>' containment reference.
   * @see #setLa_dir(LATrans)
   * @see org.team38.assembly.lC2200.LC2200Package#getLADirective_La_dir()
   * @model containment="true"
   * @generated
   */
  LATrans getLa_dir();

  /**
   * Sets the value of the '{@link org.team38.assembly.lC2200.LADirective#getLa_dir <em>La dir</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>La dir</em>' containment reference.
   * @see #getLa_dir()
   * @generated
   */
  void setLa_dir(LATrans value);

  /**
   * Returns the value of the '<em><b>Reg</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Reg</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Reg</em>' containment reference.
   * @see #setReg(RegTrans)
   * @see org.team38.assembly.lC2200.LC2200Package#getLADirective_Reg()
   * @model containment="true"
   * @generated
   */
  RegTrans getReg();

  /**
   * Sets the value of the '{@link org.team38.assembly.lC2200.LADirective#getReg <em>Reg</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Reg</em>' containment reference.
   * @see #getReg()
   * @generated
   */
  void setReg(RegTrans value);

  /**
   * Returns the value of the '<em><b>Label</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Label</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Label</em>' containment reference.
   * @see #setLabel(LabelEnd)
   * @see org.team38.assembly.lC2200.LC2200Package#getLADirective_Label()
   * @model containment="true"
   * @generated
   */
  LabelEnd getLabel();

  /**
   * Sets the value of the '{@link org.team38.assembly.lC2200.LADirective#getLabel <em>Label</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Label</em>' containment reference.
   * @see #getLabel()
   * @generated
   */
  void setLabel(LabelEnd value);

} // LADirective
