/**
 * generated by Xtext 2.9.1
 */
package org.team38.assembly.lC2200;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.team38.assembly.lC2200.LC2200Factory
 * @model kind="package"
 * @generated
 */
public interface LC2200Package extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "lC2200";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.team38.org/assembly/LC2200";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "lC2200";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  LC2200Package eINSTANCE = org.team38.assembly.lC2200.impl.LC2200PackageImpl.init();

  /**
   * The meta object id for the '{@link org.team38.assembly.lC2200.impl.ProgramImpl <em>Program</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.team38.assembly.lC2200.impl.ProgramImpl
   * @see org.team38.assembly.lC2200.impl.LC2200PackageImpl#getProgram()
   * @generated
   */
  int PROGRAM = 0;

  /**
   * The feature id for the '<em><b>Program</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM__PROGRAM = 0;

  /**
   * The number of structural features of the '<em>Program</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.team38.assembly.lC2200.impl.InstructionImpl <em>Instruction</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.team38.assembly.lC2200.impl.InstructionImpl
   * @see org.team38.assembly.lC2200.impl.LC2200PackageImpl#getInstruction()
   * @generated
   */
  int INSTRUCTION = 1;

  /**
   * The feature id for the '<em><b>Label</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSTRUCTION__LABEL = 0;

  /**
   * The feature id for the '<em><b>Instruction</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSTRUCTION__INSTRUCTION = 1;

  /**
   * The number of structural features of the '<em>Instruction</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSTRUCTION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.team38.assembly.lC2200.impl.DirectiveImpl <em>Directive</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.team38.assembly.lC2200.impl.DirectiveImpl
   * @see org.team38.assembly.lC2200.impl.LC2200PackageImpl#getDirective()
   * @generated
   */
  int DIRECTIVE = 2;

  /**
   * The feature id for the '<em><b>Label</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIRECTIVE__LABEL = 0;

  /**
   * The feature id for the '<em><b>Directive</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIRECTIVE__DIRECTIVE = 1;

  /**
   * The number of structural features of the '<em>Directive</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIRECTIVE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.team38.assembly.lC2200.impl.RInstructionImpl <em>RInstruction</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.team38.assembly.lC2200.impl.RInstructionImpl
   * @see org.team38.assembly.lC2200.impl.LC2200PackageImpl#getRInstruction()
   * @generated
   */
  int RINSTRUCTION = 3;

  /**
   * The feature id for the '<em><b>Ropcode</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RINSTRUCTION__ROPCODE = 0;

  /**
   * The number of structural features of the '<em>RInstruction</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RINSTRUCTION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.team38.assembly.lC2200.impl.IInstructionImpl <em>IInstruction</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.team38.assembly.lC2200.impl.IInstructionImpl
   * @see org.team38.assembly.lC2200.impl.LC2200PackageImpl#getIInstruction()
   * @generated
   */
  int IINSTRUCTION = 4;

  /**
   * The feature id for the '<em><b>Iopcode</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IINSTRUCTION__IOPCODE = 0;

  /**
   * The number of structural features of the '<em>IInstruction</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IINSTRUCTION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.team38.assembly.lC2200.impl.JInstructionImpl <em>JInstruction</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.team38.assembly.lC2200.impl.JInstructionImpl
   * @see org.team38.assembly.lC2200.impl.LC2200PackageImpl#getJInstruction()
   * @generated
   */
  int JINSTRUCTION = 5;

  /**
   * The feature id for the '<em><b>Jopcode</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JINSTRUCTION__JOPCODE = 0;

  /**
   * The number of structural features of the '<em>JInstruction</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JINSTRUCTION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.team38.assembly.lC2200.impl.OInstructionImpl <em>OInstruction</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.team38.assembly.lC2200.impl.OInstructionImpl
   * @see org.team38.assembly.lC2200.impl.LC2200PackageImpl#getOInstruction()
   * @generated
   */
  int OINSTRUCTION = 6;

  /**
   * The feature id for the '<em><b>Oopcode</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OINSTRUCTION__OOPCODE = 0;

  /**
   * The number of structural features of the '<em>OInstruction</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OINSTRUCTION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.team38.assembly.lC2200.impl.NOOPDirectiveImpl <em>NOOP Directive</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.team38.assembly.lC2200.impl.NOOPDirectiveImpl
   * @see org.team38.assembly.lC2200.impl.LC2200PackageImpl#getNOOPDirective()
   * @generated
   */
  int NOOP_DIRECTIVE = 7;

  /**
   * The feature id for the '<em><b>Ndir</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NOOP_DIRECTIVE__NDIR = 0;

  /**
   * The number of structural features of the '<em>NOOP Directive</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NOOP_DIRECTIVE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.team38.assembly.lC2200.impl.WordDirectiveImpl <em>Word Directive</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.team38.assembly.lC2200.impl.WordDirectiveImpl
   * @see org.team38.assembly.lC2200.impl.LC2200PackageImpl#getWordDirective()
   * @generated
   */
  int WORD_DIRECTIVE = 8;

  /**
   * The feature id for the '<em><b>Wdir</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WORD_DIRECTIVE__WDIR = 0;

  /**
   * The number of structural features of the '<em>Word Directive</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WORD_DIRECTIVE_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link org.team38.assembly.lC2200.Program <em>Program</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Program</em>'.
   * @see org.team38.assembly.lC2200.Program
   * @generated
   */
  EClass getProgram();

  /**
   * Returns the meta object for the containment reference list '{@link org.team38.assembly.lC2200.Program#getProgram <em>Program</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Program</em>'.
   * @see org.team38.assembly.lC2200.Program#getProgram()
   * @see #getProgram()
   * @generated
   */
  EReference getProgram_Program();

  /**
   * Returns the meta object for class '{@link org.team38.assembly.lC2200.Instruction <em>Instruction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Instruction</em>'.
   * @see org.team38.assembly.lC2200.Instruction
   * @generated
   */
  EClass getInstruction();

  /**
   * Returns the meta object for the attribute '{@link org.team38.assembly.lC2200.Instruction#getLabel <em>Label</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Label</em>'.
   * @see org.team38.assembly.lC2200.Instruction#getLabel()
   * @see #getInstruction()
   * @generated
   */
  EAttribute getInstruction_Label();

  /**
   * Returns the meta object for the containment reference '{@link org.team38.assembly.lC2200.Instruction#getInstruction <em>Instruction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Instruction</em>'.
   * @see org.team38.assembly.lC2200.Instruction#getInstruction()
   * @see #getInstruction()
   * @generated
   */
  EReference getInstruction_Instruction();

  /**
   * Returns the meta object for class '{@link org.team38.assembly.lC2200.Directive <em>Directive</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Directive</em>'.
   * @see org.team38.assembly.lC2200.Directive
   * @generated
   */
  EClass getDirective();

  /**
   * Returns the meta object for the attribute '{@link org.team38.assembly.lC2200.Directive#getLabel <em>Label</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Label</em>'.
   * @see org.team38.assembly.lC2200.Directive#getLabel()
   * @see #getDirective()
   * @generated
   */
  EAttribute getDirective_Label();

  /**
   * Returns the meta object for the containment reference '{@link org.team38.assembly.lC2200.Directive#getDirective <em>Directive</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Directive</em>'.
   * @see org.team38.assembly.lC2200.Directive#getDirective()
   * @see #getDirective()
   * @generated
   */
  EReference getDirective_Directive();

  /**
   * Returns the meta object for class '{@link org.team38.assembly.lC2200.RInstruction <em>RInstruction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>RInstruction</em>'.
   * @see org.team38.assembly.lC2200.RInstruction
   * @generated
   */
  EClass getRInstruction();

  /**
   * Returns the meta object for the attribute '{@link org.team38.assembly.lC2200.RInstruction#getR_opcode <em>Ropcode</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Ropcode</em>'.
   * @see org.team38.assembly.lC2200.RInstruction#getR_opcode()
   * @see #getRInstruction()
   * @generated
   */
  EAttribute getRInstruction_R_opcode();

  /**
   * Returns the meta object for class '{@link org.team38.assembly.lC2200.IInstruction <em>IInstruction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>IInstruction</em>'.
   * @see org.team38.assembly.lC2200.IInstruction
   * @generated
   */
  EClass getIInstruction();

  /**
   * Returns the meta object for the attribute '{@link org.team38.assembly.lC2200.IInstruction#getI_opcode <em>Iopcode</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Iopcode</em>'.
   * @see org.team38.assembly.lC2200.IInstruction#getI_opcode()
   * @see #getIInstruction()
   * @generated
   */
  EAttribute getIInstruction_I_opcode();

  /**
   * Returns the meta object for class '{@link org.team38.assembly.lC2200.JInstruction <em>JInstruction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>JInstruction</em>'.
   * @see org.team38.assembly.lC2200.JInstruction
   * @generated
   */
  EClass getJInstruction();

  /**
   * Returns the meta object for the attribute '{@link org.team38.assembly.lC2200.JInstruction#getJ_opcode <em>Jopcode</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Jopcode</em>'.
   * @see org.team38.assembly.lC2200.JInstruction#getJ_opcode()
   * @see #getJInstruction()
   * @generated
   */
  EAttribute getJInstruction_J_opcode();

  /**
   * Returns the meta object for class '{@link org.team38.assembly.lC2200.OInstruction <em>OInstruction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>OInstruction</em>'.
   * @see org.team38.assembly.lC2200.OInstruction
   * @generated
   */
  EClass getOInstruction();

  /**
   * Returns the meta object for the attribute '{@link org.team38.assembly.lC2200.OInstruction#getO_opcode <em>Oopcode</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Oopcode</em>'.
   * @see org.team38.assembly.lC2200.OInstruction#getO_opcode()
   * @see #getOInstruction()
   * @generated
   */
  EAttribute getOInstruction_O_opcode();

  /**
   * Returns the meta object for class '{@link org.team38.assembly.lC2200.NOOPDirective <em>NOOP Directive</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>NOOP Directive</em>'.
   * @see org.team38.assembly.lC2200.NOOPDirective
   * @generated
   */
  EClass getNOOPDirective();

  /**
   * Returns the meta object for the attribute '{@link org.team38.assembly.lC2200.NOOPDirective#getN_dir <em>Ndir</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Ndir</em>'.
   * @see org.team38.assembly.lC2200.NOOPDirective#getN_dir()
   * @see #getNOOPDirective()
   * @generated
   */
  EAttribute getNOOPDirective_N_dir();

  /**
   * Returns the meta object for class '{@link org.team38.assembly.lC2200.WordDirective <em>Word Directive</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Word Directive</em>'.
   * @see org.team38.assembly.lC2200.WordDirective
   * @generated
   */
  EClass getWordDirective();

  /**
   * Returns the meta object for the attribute '{@link org.team38.assembly.lC2200.WordDirective#getW_dir <em>Wdir</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Wdir</em>'.
   * @see org.team38.assembly.lC2200.WordDirective#getW_dir()
   * @see #getWordDirective()
   * @generated
   */
  EAttribute getWordDirective_W_dir();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  LC2200Factory getLC2200Factory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.team38.assembly.lC2200.impl.ProgramImpl <em>Program</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.team38.assembly.lC2200.impl.ProgramImpl
     * @see org.team38.assembly.lC2200.impl.LC2200PackageImpl#getProgram()
     * @generated
     */
    EClass PROGRAM = eINSTANCE.getProgram();

    /**
     * The meta object literal for the '<em><b>Program</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROGRAM__PROGRAM = eINSTANCE.getProgram_Program();

    /**
     * The meta object literal for the '{@link org.team38.assembly.lC2200.impl.InstructionImpl <em>Instruction</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.team38.assembly.lC2200.impl.InstructionImpl
     * @see org.team38.assembly.lC2200.impl.LC2200PackageImpl#getInstruction()
     * @generated
     */
    EClass INSTRUCTION = eINSTANCE.getInstruction();

    /**
     * The meta object literal for the '<em><b>Label</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INSTRUCTION__LABEL = eINSTANCE.getInstruction_Label();

    /**
     * The meta object literal for the '<em><b>Instruction</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INSTRUCTION__INSTRUCTION = eINSTANCE.getInstruction_Instruction();

    /**
     * The meta object literal for the '{@link org.team38.assembly.lC2200.impl.DirectiveImpl <em>Directive</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.team38.assembly.lC2200.impl.DirectiveImpl
     * @see org.team38.assembly.lC2200.impl.LC2200PackageImpl#getDirective()
     * @generated
     */
    EClass DIRECTIVE = eINSTANCE.getDirective();

    /**
     * The meta object literal for the '<em><b>Label</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DIRECTIVE__LABEL = eINSTANCE.getDirective_Label();

    /**
     * The meta object literal for the '<em><b>Directive</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DIRECTIVE__DIRECTIVE = eINSTANCE.getDirective_Directive();

    /**
     * The meta object literal for the '{@link org.team38.assembly.lC2200.impl.RInstructionImpl <em>RInstruction</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.team38.assembly.lC2200.impl.RInstructionImpl
     * @see org.team38.assembly.lC2200.impl.LC2200PackageImpl#getRInstruction()
     * @generated
     */
    EClass RINSTRUCTION = eINSTANCE.getRInstruction();

    /**
     * The meta object literal for the '<em><b>Ropcode</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RINSTRUCTION__ROPCODE = eINSTANCE.getRInstruction_R_opcode();

    /**
     * The meta object literal for the '{@link org.team38.assembly.lC2200.impl.IInstructionImpl <em>IInstruction</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.team38.assembly.lC2200.impl.IInstructionImpl
     * @see org.team38.assembly.lC2200.impl.LC2200PackageImpl#getIInstruction()
     * @generated
     */
    EClass IINSTRUCTION = eINSTANCE.getIInstruction();

    /**
     * The meta object literal for the '<em><b>Iopcode</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute IINSTRUCTION__IOPCODE = eINSTANCE.getIInstruction_I_opcode();

    /**
     * The meta object literal for the '{@link org.team38.assembly.lC2200.impl.JInstructionImpl <em>JInstruction</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.team38.assembly.lC2200.impl.JInstructionImpl
     * @see org.team38.assembly.lC2200.impl.LC2200PackageImpl#getJInstruction()
     * @generated
     */
    EClass JINSTRUCTION = eINSTANCE.getJInstruction();

    /**
     * The meta object literal for the '<em><b>Jopcode</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute JINSTRUCTION__JOPCODE = eINSTANCE.getJInstruction_J_opcode();

    /**
     * The meta object literal for the '{@link org.team38.assembly.lC2200.impl.OInstructionImpl <em>OInstruction</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.team38.assembly.lC2200.impl.OInstructionImpl
     * @see org.team38.assembly.lC2200.impl.LC2200PackageImpl#getOInstruction()
     * @generated
     */
    EClass OINSTRUCTION = eINSTANCE.getOInstruction();

    /**
     * The meta object literal for the '<em><b>Oopcode</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OINSTRUCTION__OOPCODE = eINSTANCE.getOInstruction_O_opcode();

    /**
     * The meta object literal for the '{@link org.team38.assembly.lC2200.impl.NOOPDirectiveImpl <em>NOOP Directive</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.team38.assembly.lC2200.impl.NOOPDirectiveImpl
     * @see org.team38.assembly.lC2200.impl.LC2200PackageImpl#getNOOPDirective()
     * @generated
     */
    EClass NOOP_DIRECTIVE = eINSTANCE.getNOOPDirective();

    /**
     * The meta object literal for the '<em><b>Ndir</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NOOP_DIRECTIVE__NDIR = eINSTANCE.getNOOPDirective_N_dir();

    /**
     * The meta object literal for the '{@link org.team38.assembly.lC2200.impl.WordDirectiveImpl <em>Word Directive</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.team38.assembly.lC2200.impl.WordDirectiveImpl
     * @see org.team38.assembly.lC2200.impl.LC2200PackageImpl#getWordDirective()
     * @generated
     */
    EClass WORD_DIRECTIVE = eINSTANCE.getWordDirective();

    /**
     * The meta object literal for the '<em><b>Wdir</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WORD_DIRECTIVE__WDIR = eINSTANCE.getWordDirective_W_dir();

  }

} //LC2200Package
