/**
 * generated by Xtext 2.9.1
 */
package org.team38.assembly.lC2200;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Reg Trans</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link org.team38.assembly.lC2200.RegTrans#getReg <em>Reg</em>}</li>
 * </ul>
 * </p>
 *
 * @see org.team38.assembly.lC2200.LC2200Package#getRegTrans()
 * @model
 * @generated
 */
public interface RegTrans extends EObject
{
  /**
   * Returns the value of the '<em><b>Reg</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Reg</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Reg</em>' attribute.
   * @see #setReg(String)
   * @see org.team38.assembly.lC2200.LC2200Package#getRegTrans_Reg()
   * @model
   * @generated
   */
  String getReg();

  /**
   * Sets the value of the '{@link org.team38.assembly.lC2200.RegTrans#getReg <em>Reg</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Reg</em>' attribute.
   * @see #getReg()
   * @generated
   */
  void setReg(String value);

} // RegTrans
