/**
 * generated by Xtext 2.9.1
 */
package org.team38.assembly.lC2200;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>RInstruction Trans</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link org.team38.assembly.lC2200.RInstructionTrans#getR_opcode <em>Ropcode</em>}</li>
 * </ul>
 * </p>
 *
 * @see org.team38.assembly.lC2200.LC2200Package#getRInstructionTrans()
 * @model
 * @generated
 */
public interface RInstructionTrans extends EObject
{
  /**
   * Returns the value of the '<em><b>Ropcode</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Ropcode</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ropcode</em>' attribute.
   * @see #setR_opcode(String)
   * @see org.team38.assembly.lC2200.LC2200Package#getRInstructionTrans_R_opcode()
   * @model
   * @generated
   */
  String getR_opcode();

  /**
   * Sets the value of the '{@link org.team38.assembly.lC2200.RInstructionTrans#getR_opcode <em>Ropcode</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ropcode</em>' attribute.
   * @see #getR_opcode()
   * @generated
   */
  void setR_opcode(String value);

} // RInstructionTrans
