/**
 * generated by Xtext 2.9.1
 */
package org.team38.assembly.lC2200;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Word Trans</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.team38.assembly.lC2200.WordTrans#getWord <em>Word</em>}</li>
 * </ul>
 *
 * @see org.team38.assembly.lC2200.LC2200Package#getWordTrans()
 * @model
 * @generated
 */
public interface WordTrans extends EObject
{
  /**
   * Returns the value of the '<em><b>Word</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Word</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Word</em>' attribute.
   * @see #setWord(String)
   * @see org.team38.assembly.lC2200.LC2200Package#getWordTrans_Word()
   * @model
   * @generated
   */
  String getWord();

  /**
   * Sets the value of the '{@link org.team38.assembly.lC2200.WordTrans#getWord <em>Word</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Word</em>' attribute.
   * @see #getWord()
   * @generated
   */
  void setWord(String value);

} // WordTrans
