/**
 * generated by Xtext 2.9.1
 */
package org.team38.assembly.lC2200;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Word Directive</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.team38.assembly.lC2200.WordDirective#getW_dir <em>Wdir</em>}</li>
 *   <li>{@link org.team38.assembly.lC2200.WordDirective#getImm <em>Imm</em>}</li>
 * </ul>
 *
 * @see org.team38.assembly.lC2200.LC2200Package#getWordDirective()
 * @model
 * @generated
 */
public interface WordDirective extends EObject
{
  /**
   * Returns the value of the '<em><b>Wdir</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Wdir</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Wdir</em>' containment reference.
   * @see #setW_dir(WordTrans)
   * @see org.team38.assembly.lC2200.LC2200Package#getWordDirective_W_dir()
   * @model containment="true"
   * @generated
   */
  WordTrans getW_dir();

  /**
   * Sets the value of the '{@link org.team38.assembly.lC2200.WordDirective#getW_dir <em>Wdir</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Wdir</em>' containment reference.
   * @see #getW_dir()
   * @generated
   */
  void setW_dir(WordTrans value);

  /**
   * Returns the value of the '<em><b>Imm</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Imm</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Imm</em>' attribute.
   * @see #setImm(String)
   * @see org.team38.assembly.lC2200.LC2200Package#getWordDirective_Imm()
   * @model
   * @generated
   */
  String getImm();

  /**
   * Sets the value of the '{@link org.team38.assembly.lC2200.WordDirective#getImm <em>Imm</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Imm</em>' attribute.
   * @see #getImm()
   * @generated
   */
  void setImm(String value);

} // WordDirective
